# Cargo-auto.readme

# This is not a standard cargo workspace. It does not have Cargo.toml in the workspace folder.
# Because of one WASM project I cannot use the profile panic="abort" on all the members.
# There is no workaround as of 2022-10-20.

# We can use cargo-auto to automate the tasks for every member individually.
# Then we code the automation_tasks_rs on the workspace level to call all members tasks together.
# The presence of Cargo.toml is used by cargo-auto to recognize project folders.
